CREATE   PROCEDURE sp_Load_DimItemHash
AS
BEGIN
    -- =====================================================
    -- INSERT: Add new rows that don't exist in gold
    -- =====================================================
    PRINT 'INSERT STARTED';
    INSERT INTO [WH].[gold].[Item27] (
        [WTIAAllocJnlUnitofMeasure],[VendorItemNo],[WCINV08WHItemNo],
        [WTUSSalesLimAllocMethod],[LeadTimeCalculation],[WTBAClosureTypeCode],
        [WTBASubRegionCode],[WarehouseClassCode],[ItemDiscGroup],[WTBAWineColor],
        [WTUSCOLANo],[WTBAOriginRegionCode-87005],[WTBAVarietalCode],[WTBABrandNo],
        [WTBAVintageCode],[WTBAAlcoholTypeCode],[WCINV04PurchaserCode],[WTBALabelCode],
        [CountryRegionofOriginCode],[WCINV14ItemPortfolio],[GenProdPostingGroup],
        [InventoryPostingGroup],[VendorNo],[WTBABottleSize],[$Company],
        [AllowInvoiceDisc],[AllowOnlineAdjustment],[BaseUnitofMeasure],[Blocked],
        [Description],[ItemCategoryCode],[LastDateModified],[LastDateTimeModified],
        [LastDirectCost],[LastTimeModified],[NetWeight],[No],[PurchasingBlocked],
        [SalesUnitofMeasure],[SearchDescription],[StandardCost],[SystemCreatedAt],
        [SystemCreatedBy],[SystemModifiedAt],[UnitCost],[UnitListPrice],[UnitPrice],
        [UnitVolume],[UseCrossDocking],[WCAR06SalesCommissionable],[WCINT02ExportedtoJFHB],
        [WCINT03ExportedtoMMK],[WCINT04PABlocked],[WCINT04SplitAllowed],
        [WCINV08AgedInventory],[WCINV08ExpectedQtyfromVend],[WCINV08NAforSalesreps],
        [WCINV08SuggestedRetailPrice],[WCINV19DonotPrintonCat],[WCSAL04AllowPalletDiscount],
        [WCSAL04AllowSampleDiscount],[WCTEWPrestige],[WTBAAlcoholContent],[WTBABiodynamic],
        [WTBACasePack],[WTBACasesperPallet],[WTBACasesperPalletLayer],[WTBADoNotAllowSamples],
        [WTBAExclfromSampleBudget],[WTBALastDirectCostBottle],[WTBALastDirectCostCase],
        [WTBALayersperPallet],[WTBAOrganic],[WTBAProof],[WTBASalesOrderReview],
        [WTBAStandardCostBottle],[WTBAStandardCostCase],[WTBAUnitCostBottle],[WTBAUnitCostCase],
        [WTBAVegan],[WTIAAllocate],[WTIAAllocationReservInt],[WTIAAllocationisCurrent],
        [WTIAFullAllocationRequired],[WTIALimitingQtyperSource],[WTIALimitingUnitType],
        [WTUSDonotPricePost],[WTUSSalesLimitation],[systemId],[timestamp],[InsertDate]
    )
    SELECT
        s.[WTIAAllocJnlUnitofMeasure-90107],s.[VendorItemNo-32],s.[WCINV08WHItemNo-50045],
        s.[WTUSSalesLimAllocMethod-88035],s.[LeadTimeCalculation-33],s.[WTBAClosureTypeCode-87065],
        s.[WTBASubRegionCode-87006],s.[WarehouseClassCode-7300],s.[ItemDiscGroup-14],
        s.[WTBAWineColor-87025],s.[WTUSCOLANo-88500],s.[WTBAOriginRegionCode-87005],
        s.[WTBAVarietalCode-87007],s.[WTBABrandNo-87150],s.[WTBAVintageCode-87000],
        s.[WTBAAlcoholTypeCode-87015],s.[WCINV04PurchaserCode-50010],s.[WTBALabelCode-87080],
        s.[CountryRegionofOriginCode-95],s.[WCINV14ItemPortfolio-50150],s.[GenProdPostingGroup-91],
        s.[InventoryPostingGroup-11],s.[VendorNo-31],s.[WTBABottleSize-87020],s.[$Company],
        s.[AllowInvoiceDisc-15],s.[AllowOnlineAdjustment-30],s.[BaseUnitofMeasure-8],
        s.[Blocked-54],s.[Description-3],s.[ItemCategoryCode-5702],s.[LastDateModified-62],
        s.[LastDateTimeModified-61],s.[LastDirectCost-25],s.[LastTimeModified-63],
        s.[NetWeight-42],s.[No-1],s.[PurchasingBlocked-8004],s.[SalesUnitofMeasure-5425],
        s.[SearchDescription-4],s.[StandardCost-24],s.[SystemCreatedAt-2000000001],
        s.[SystemCreatedBy-2000000002],s.[SystemModifiedAt-2000000003],s.[UnitCost-22],
        s.[UnitListPrice-38],s.[UnitPrice-18],s.[UnitVolume-44],s.[UseCrossDocking-7384],
        s.[WCAR06SalesCommissionable-50100],s.[WCINT02ExportedtoJFHB-50250],
        s.[WCINT03ExportedtoMMK-50280],s.[WCINT04PABlocked-50650],s.[WCINT04SplitAllowed-50651],
        s.[WCINV08AgedInventory-50043],s.[WCINV08ExpectedQtyfromVend-50044],
        s.[WCINV08NAforSalesreps-50046],s.[WCINV08SuggestedRetailPrice-50047],
        s.[WCINV19DonotPrintonCat-50520],s.[WCSAL04AllowPalletDiscount-50121],
        s.[WCSAL04AllowSampleDiscount-50120],s.[WCTEWPrestige-50000],
        s.[WTBAAlcoholContent-87030],s.[WTBABiodynamic-87064],s.[WTBACasePack-87010],
        s.[WTBACasesperPallet-87096],s.[WTBACasesperPalletLayer-87090],
        s.[WTBADoNotAllowSamples-87700],s.[WTBAExclfromSampleBudget-87701],
        s.[WTBALastDirectCostBottle-87116],s.[WTBALastDirectCostCase-87115],
        s.[WTBALayersperPallet-87095],s.[WTBAOrganic-87063],s.[WTBAProof-87031],
        s.[WTBASalesOrderReview-87850],s.[WTBAStandardCostBottle-87121],
        s.[WTBAStandardCostCase-87120],s.[WTBAUnitCostBottle-87111],s.[WTBAUnitCostCase-87110],
        s.[WTBAVegan-87062],s.[WTIAAllocate-90100],s.[WTIAAllocationReservInt-90102],
        s.[WTIAAllocationisCurrent-90104],s.[WTIAFullAllocationRequired-90101],
        s.[WTIALimitingQtyperSource-90130],s.[WTIALimitingUnitType-90140],
        s.[WTUSDonotPricePost-88800],s.[WTUSSalesLimitation-88030],
        s.[systemId-2000000000],s.[timestamp-0],GETDATE()
    FROM [Rahat_LH].[dbo].[item] s
    LEFT JOIN [WH].[gold].[Item27] t ON s.[No-1] = t.[No]
    WHERE t.[No] IS NULL;

    -- =====================================================
    -- HASH CTE: Compute SHA2_256 hash for source and gold
    -- All columns cast to VARCHAR for consistent hashing
    -- =====================================================
    PRINT 'UPDATE STARTED';

    WITH src_hash AS (
        SELECT
            [No-1] AS [No],
            HASHBYTES('SHA2_256',
                CONCAT(
                    ISNULL([WTIAAllocJnlUnitofMeasure-90107],''),     '|',
                    ISNULL([VendorItemNo-32],''),                      '|',
                    ISNULL([WCINV08WHItemNo-50045],''),                '|',
                    ISNULL([WTUSSalesLimAllocMethod-88035],''),        '|',
                    ISNULL([LeadTimeCalculation-33],''),               '|',
                    ISNULL([WTBAClosureTypeCode-87065],''),            '|',
                    ISNULL([WTBASubRegionCode-87006],''),              '|',
                    ISNULL([WarehouseClassCode-7300],''),              '|',
                    ISNULL([ItemDiscGroup-14],''),                     '|',
                    ISNULL([WTBAWineColor-87025],''),                  '|',
                    ISNULL([WTUSCOLANo-88500],''),                     '|',
                    ISNULL([WTBAOriginRegionCode-87005],''),           '|',
                    ISNULL([WTBAVarietalCode-87007],''),               '|',
                    ISNULL([WTBABrandNo-87150],''),                    '|',
                    ISNULL([WTBAVintageCode-87000],''),                '|',
                    ISNULL([WTBAAlcoholTypeCode-87015],''),            '|',
                    ISNULL([WCINV04PurchaserCode-50010],''),           '|',
                    ISNULL([WTBALabelCode-87080],''),                  '|',
                    ISNULL([CountryRegionofOriginCode-95],''),         '|',
                    ISNULL([WCINV14ItemPortfolio-50150],''),           '|',
                    ISNULL([GenProdPostingGroup-91],''),               '|',
                    ISNULL([InventoryPostingGroup-11],''),             '|',
                    ISNULL([VendorNo-31],''),                          '|',
                    ISNULL([WTBABottleSize-87020],''),                 '|',
                    ISNULL([$Company],''),                             '|',
                    ISNULL(CAST([AllowInvoiceDisc-15]    AS VARCHAR),''), '|',
                    ISNULL(CAST([AllowOnlineAdjustment-30] AS VARCHAR),''),'|',
                    ISNULL([BaseUnitofMeasure-8],''),                  '|',
                    ISNULL(CAST([Blocked-54]             AS VARCHAR),''), '|',
                    ISNULL([Description-3],''),                        '|',
                    ISNULL([ItemCategoryCode-5702],''),                '|',
                    ISNULL(CONVERT(VARCHAR,[LastDateModified-62],120),''),     '|',
                    ISNULL(CONVERT(VARCHAR,[LastDateTimeModified-61],120),''), '|',
                    ISNULL(CAST([LastDirectCost-25]      AS VARCHAR),''), '|',
                    ISNULL([LastTimeModified-63],''),                  '|',
                    ISNULL(CAST([NetWeight-42]            AS VARCHAR),''), '|',
                    ISNULL(CAST([PurchasingBlocked-8004] AS VARCHAR),''), '|',
                    ISNULL([SalesUnitofMeasure-5425],''),              '|',
                    ISNULL([SearchDescription-4],''),                  '|',
                    ISNULL(CAST([StandardCost-24]        AS VARCHAR),''), '|',
                    ISNULL(CONVERT(VARCHAR,[SystemCreatedAt-2000000001],120),''),  '|',
                    ISNULL([SystemCreatedBy-2000000002],''),           '|',
                    ISNULL(CONVERT(VARCHAR,[SystemModifiedAt-2000000003],120),''), '|',
                    ISNULL(CAST([UnitCost-22]            AS VARCHAR),''), '|',
                    ISNULL(CAST([UnitListPrice-38]       AS VARCHAR),''), '|',
                    ISNULL(CAST([UnitPrice-18]           AS VARCHAR),''), '|',
                    ISNULL(CAST([UnitVolume-44]          AS VARCHAR),''), '|',
                    ISNULL(CAST([UseCrossDocking-7384]   AS VARCHAR),''), '|',
                    ISNULL(CAST([WCAR06SalesCommissionable-50100] AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINT02ExportedtoJFHB-50250]    AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINT03ExportedtoMMK-50280]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINT04PABlocked-50650]         AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINT04SplitAllowed-50651]      AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINV08AgedInventory-50043]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINV08ExpectedQtyfromVend-50044] AS VARCHAR),''),'|',
                    ISNULL(CAST([WCINV08NAforSalesreps-50046]    AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINV08SuggestedRetailPrice-50047] AS VARCHAR),''),'|',
                    ISNULL(CAST([WCINV19DonotPrintonCat-50520]   AS VARCHAR),''), '|',
                    ISNULL(CAST([WCSAL04AllowPalletDiscount-50121] AS VARCHAR),''),'|',
                    ISNULL(CAST([WCSAL04AllowSampleDiscount-50120] AS VARCHAR),''),'|',
                    ISNULL(CAST([WCTEWPrestige-50000]            AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAAlcoholContent-87030]       AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBABiodynamic-87064]           AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBACasePack-87010]             AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBACasesperPallet-87096]       AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBACasesperPalletLayer-87090]  AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBADoNotAllowSamples-87700]    AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAExclfromSampleBudget-87701] AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBALastDirectCostBottle-87116] AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBALastDirectCostCase-87115]   AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBALayersperPallet-87095]      AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAOrganic-87063]              AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAProof-87031]                AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBASalesOrderReview-87850]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAStandardCostBottle-87121]   AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAStandardCostCase-87120]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAUnitCostBottle-87111]       AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAUnitCostCase-87110]         AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAVegan-87062]                AS VARCHAR),''), '|',
                    ISNULL(CAST([WTIAAllocate-90100]             AS VARCHAR),''), '|',
                    ISNULL([WTIAAllocationReservInt-90102],''),                   '|',
                    ISNULL(CAST([WTIAAllocationisCurrent-90104]  AS VARCHAR),''), '|',
                    ISNULL(CAST([WTIAFullAllocationRequired-90101] AS VARCHAR),''),'|',
                    ISNULL(CAST([WTIALimitingQtyperSource-90130] AS VARCHAR),''), '|',
                    ISNULL([WTIALimitingUnitType-90140],''),                      '|',
                    ISNULL(CAST([WTUSDonotPricePost-88800]       AS VARCHAR),''), '|',
                    ISNULL([WTUSSalesLimitation-88030],''),                       '|',
                    ISNULL([systemId-2000000000],''),                             '|',
                    ISNULL(CAST([timestamp-0]                    AS VARCHAR),'')
                )
            ) AS src_hash
        FROM [Rahat_LH].[dbo].[item]
    ),
    dst_hash AS (
        SELECT
            [No],
            HASHBYTES('SHA2_256',
                CONCAT(
                    ISNULL([WTIAAllocJnlUnitofMeasure],''),   '|',
                    ISNULL([VendorItemNo],''),                 '|',
                    ISNULL([WCINV08WHItemNo],''),              '|',
                    ISNULL([WTUSSalesLimAllocMethod],''),      '|',
                    ISNULL([LeadTimeCalculation],''),          '|',
                    ISNULL([WTBAClosureTypeCode],''),          '|',
                    ISNULL([WTBASubRegionCode],''),            '|',
                    ISNULL([WarehouseClassCode],''),           '|',
                    ISNULL([ItemDiscGroup],''),                '|',
                    ISNULL([WTBAWineColor],''),                '|',
                    ISNULL([WTUSCOLANo],''),                   '|',
                    ISNULL([WTBAOriginRegionCode-87005],''),   '|',
                    ISNULL([WTBAVarietalCode],''),             '|',
                    ISNULL([WTBABrandNo],''),                  '|',
                    ISNULL([WTBAVintageCode],''),              '|',
                    ISNULL([WTBAAlcoholTypeCode],''),          '|',
                    ISNULL([WCINV04PurchaserCode],''),         '|',
                    ISNULL([WTBALabelCode],''),                '|',
                    ISNULL([CountryRegionofOriginCode],''),    '|',
                    ISNULL([WCINV14ItemPortfolio],''),         '|',
                    ISNULL([GenProdPostingGroup],''),          '|',
                    ISNULL([InventoryPostingGroup],''),        '|',
                    ISNULL([VendorNo],''),                     '|',
                    ISNULL([WTBABottleSize],''),               '|',
                    ISNULL([$Company],''),                     '|',
                    ISNULL(CAST([AllowInvoiceDisc]    AS VARCHAR),''), '|',
                    ISNULL(CAST([AllowOnlineAdjustment] AS VARCHAR),''),'|',
                    ISNULL([BaseUnitofMeasure],''),            '|',
                    ISNULL(CAST([Blocked]             AS VARCHAR),''), '|',
                    ISNULL([Description],''),                  '|',
                    ISNULL([ItemCategoryCode],''),             '|',
                    ISNULL(CONVERT(VARCHAR,[LastDateModified],120),''),     '|',
                    ISNULL(CONVERT(VARCHAR,[LastDateTimeModified],120),''), '|',
                    ISNULL(CAST([LastDirectCost]      AS VARCHAR),''), '|',
                    ISNULL([LastTimeModified],''),             '|',
                    ISNULL(CAST([NetWeight]            AS VARCHAR),''), '|',
                    ISNULL(CAST([PurchasingBlocked]   AS VARCHAR),''), '|',
                    ISNULL([SalesUnitofMeasure],''),           '|',
                    ISNULL([SearchDescription],''),            '|',
                    ISNULL(CAST([StandardCost]        AS VARCHAR),''), '|',
                    ISNULL(CONVERT(VARCHAR,[SystemCreatedAt],120),''),  '|',
                    ISNULL([SystemCreatedBy],''),              '|',
                    ISNULL(CONVERT(VARCHAR,[SystemModifiedAt],120),''), '|',
                    ISNULL(CAST([UnitCost]            AS VARCHAR),''), '|',
                    ISNULL(CAST([UnitListPrice]       AS VARCHAR),''), '|',
                    ISNULL(CAST([UnitPrice]           AS VARCHAR),''), '|',
                    ISNULL(CAST([UnitVolume]          AS VARCHAR),''), '|',
                    ISNULL(CAST([UseCrossDocking]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WCAR06SalesCommissionable] AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINT02ExportedtoJFHB]    AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINT03ExportedtoMMK]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINT04PABlocked]         AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINT04SplitAllowed]      AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINV08AgedInventory]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINV08ExpectedQtyfromVend] AS VARCHAR),''),'|',
                    ISNULL(CAST([WCINV08NAforSalesreps]    AS VARCHAR),''), '|',
                    ISNULL(CAST([WCINV08SuggestedRetailPrice] AS VARCHAR),''),'|',
                    ISNULL(CAST([WCINV19DonotPrintonCat]   AS VARCHAR),''), '|',
                    ISNULL(CAST([WCSAL04AllowPalletDiscount] AS VARCHAR),''),'|',
                    ISNULL(CAST([WCSAL04AllowSampleDiscount] AS VARCHAR),''),'|',
                    ISNULL(CAST([WCTEWPrestige]            AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAAlcoholContent]       AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBABiodynamic]           AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBACasePack]             AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBACasesperPallet]       AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBACasesperPalletLayer]  AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBADoNotAllowSamples]    AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAExclfromSampleBudget] AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBALastDirectCostBottle] AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBALastDirectCostCase]   AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBALayersperPallet]      AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAOrganic]              AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAProof]                AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBASalesOrderReview]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAStandardCostBottle]   AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAStandardCostCase]     AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAUnitCostBottle]       AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAUnitCostCase]         AS VARCHAR),''), '|',
                    ISNULL(CAST([WTBAVegan]                AS VARCHAR),''), '|',
                    ISNULL(CAST([WTIAAllocate]             AS VARCHAR),''), '|',
                    ISNULL([WTIAAllocationReservInt],''),                   '|',
                    ISNULL(CAST([WTIAAllocationisCurrent]  AS VARCHAR),''), '|',
                    ISNULL(CAST([WTIAFullAllocationRequired] AS VARCHAR),''),'|',
                    ISNULL(CAST([WTIALimitingQtyperSource] AS VARCHAR),''), '|',
                    ISNULL([WTIALimitingUnitType],''),                      '|',
                    ISNULL(CAST([WTUSDonotPricePost]       AS VARCHAR),''), '|',
                    ISNULL([WTUSSalesLimitation],''),                       '|',
                    ISNULL([systemId],''),                                  '|',
                    ISNULL(CAST([timestamp]                AS VARCHAR),'')
                )
            ) AS dst_hash
        FROM [WH].[gold].[Item27]
    )

    -- =====================================================
    -- VALIDATION REPORT: Show mismatch count before update
    -- =====================================================
    SELECT
        COUNT(*)                                           AS TotalSourceRows,
        SUM(CASE WHEN s.src_hash <> d.dst_hash THEN 1 ELSE 0 END) AS RowsWithChanges,
        SUM(CASE WHEN s.src_hash =  d.dst_hash THEN 1 ELSE 0 END) AS RowsUnchanged,
        SUM(CASE WHEN d.[No] IS NULL             THEN 1 ELSE 0 END) AS NewRows
    FROM src_hash s
    LEFT JOIN dst_hash d ON s.[No] = d.[No];

    -- =====================================================
    -- UPDATE: Only rows where hash differs
    -- =====================================================
    UPDATE t
    SET
        t.[WTIAAllocJnlUnitofMeasure]  = s.[WTIAAllocJnlUnitofMeasure-90107],
        t.[VendorItemNo]               = s.[VendorItemNo-32],
        t.[WCINV08WHItemNo]            = s.[WCINV08WHItemNo-50045],
        t.[WTUSSalesLimAllocMethod]    = s.[WTUSSalesLimAllocMethod-88035],
        t.[LeadTimeCalculation]        = s.[LeadTimeCalculation-33],
        t.[WTBAClosureTypeCode]        = s.[WTBAClosureTypeCode-87065],
        t.[WTBASubRegionCode]          = s.[WTBASubRegionCode-87006],
        t.[WarehouseClassCode]         = s.[WarehouseClassCode-7300],
        t.[ItemDiscGroup]              = s.[ItemDiscGroup-14],
        t.[WTBAWineColor]              = s.[WTBAWineColor-87025],
        t.[WTUSCOLANo]                 = s.[WTUSCOLANo-88500],
        t.[WTBAOriginRegionCode-87005] = s.[WTBAOriginRegionCode-87005],
        t.[WTBAVarietalCode]           = s.[WTBAVarietalCode-87007],
        t.[WTBABrandNo]                = s.[WTBABrandNo-87150],
        t.[WTBAVintageCode]            = s.[WTBAVintageCode-87000],
        t.[WTBAAlcoholTypeCode]        = s.[WTBAAlcoholTypeCode-87015],
        t.[WCINV04PurchaserCode]       = s.[WCINV04PurchaserCode-50010],
        t.[WTBALabelCode]              = s.[WTBALabelCode-87080],
        t.[CountryRegionofOriginCode]  = s.[CountryRegionofOriginCode-95],
        t.[WCINV14ItemPortfolio]       = s.[WCINV14ItemPortfolio-50150],
        t.[GenProdPostingGroup]        = s.[GenProdPostingGroup-91],
        t.[InventoryPostingGroup]      = s.[InventoryPostingGroup-11],
        t.[VendorNo]                   = s.[VendorNo-31],
        t.[WTBABottleSize]             = s.[WTBABottleSize-87020],
        t.[$Company]                   = s.[$Company],
        t.[AllowInvoiceDisc]           = s.[AllowInvoiceDisc-15],
        t.[AllowOnlineAdjustment]      = s.[AllowOnlineAdjustment-30],
        t.[BaseUnitofMeasure]          = s.[BaseUnitofMeasure-8],
        t.[Blocked]                    = s.[Blocked-54],
        t.[Description]                = s.[Description-3],
        t.[ItemCategoryCode]           = s.[ItemCategoryCode-5702],
        t.[LastDateModified]           = s.[LastDateModified-62],
        t.[LastDateTimeModified]       = s.[LastDateTimeModified-61],
        t.[LastDirectCost]             = s.[LastDirectCost-25],
        t.[LastTimeModified]           = s.[LastTimeModified-63],
        t.[NetWeight]                  = s.[NetWeight-42],
        t.[PurchasingBlocked]          = s.[PurchasingBlocked-8004],
        t.[SalesUnitofMeasure]         = s.[SalesUnitofMeasure-5425],
        t.[SearchDescription]          = s.[SearchDescription-4],
        t.[StandardCost]               = s.[StandardCost-24],
        t.[SystemCreatedAt]            = s.[SystemCreatedAt-2000000001],
        t.[SystemCreatedBy]            = s.[SystemCreatedBy-2000000002],
        t.[SystemModifiedAt]           = s.[SystemModifiedAt-2000000003],
        t.[UnitCost]                   = s.[UnitCost-22],
        t.[UnitListPrice]              = s.[UnitListPrice-38],
        t.[UnitPrice]                  = s.[UnitPrice-18],
        t.[UnitVolume]                 = s.[UnitVolume-44],
        t.[UseCrossDocking]            = s.[UseCrossDocking-7384],
        t.[WCAR06SalesCommissionable]  = s.[WCAR06SalesCommissionable-50100],
        t.[WCINT02ExportedtoJFHB]      = s.[WCINT02ExportedtoJFHB-50250],
        t.[WCINT03ExportedtoMMK]       = s.[WCINT03ExportedtoMMK-50280],
        t.[WCINT04PABlocked]           = s.[WCINT04PABlocked-50650],
        t.[WCINT04SplitAllowed]        = s.[WCINT04SplitAllowed-50651],
        t.[WCINV08AgedInventory]       = s.[WCINV08AgedInventory-50043],
        t.[WCINV08ExpectedQtyfromVend] = s.[WCINV08ExpectedQtyfromVend-50044],
        t.[WCINV08NAforSalesreps]      = s.[WCINV08NAforSalesreps-50046],
        t.[WCINV08SuggestedRetailPrice]= s.[WCINV08SuggestedRetailPrice-50047],
        t.[WCINV19DonotPrintonCat]     = s.[WCINV19DonotPrintonCat-50520],
        t.[WCSAL04AllowPalletDiscount] = s.[WCSAL04AllowPalletDiscount-50121],
        t.[WCSAL04AllowSampleDiscount] = s.[WCSAL04AllowSampleDiscount-50120],
        t.[WCTEWPrestige]              = s.[WCTEWPrestige-50000],
        t.[WTBAAlcoholContent]         = s.[WTBAAlcoholContent-87030],
        t.[WTBABiodynamic]             = s.[WTBABiodynamic-87064],
        t.[WTBACasePack]               = s.[WTBACasePack-87010],
        t.[WTBACasesperPallet]         = s.[WTBACasesperPallet-87096],
        t.[WTBACasesperPalletLayer]    = s.[WTBACasesperPalletLayer-87090],
        t.[WTBADoNotAllowSamples]      = s.[WTBADoNotAllowSamples-87700],
        t.[WTBAExclfromSampleBudget]   = s.[WTBAExclfromSampleBudget-87701],
        t.[WTBALastDirectCostBottle]   = s.[WTBALastDirectCostBottle-87116],
        t.[WTBALastDirectCostCase]     = s.[WTBALastDirectCostCase-87115],
        t.[WTBALayersperPallet]        = s.[WTBALayersperPallet-87095],
        t.[WTBAOrganic]                = s.[WTBAOrganic-87063],
        t.[WTBAProof]                  = s.[WTBAProof-87031],
        t.[WTBASalesOrderReview]       = s.[WTBASalesOrderReview-87850],
        t.[WTBAStandardCostBottle]     = s.[WTBAStandardCostBottle-87121],
        t.[WTBAStandardCostCase]       = s.[WTBAStandardCostCase-87120],
        t.[WTBAUnitCostBottle]         = s.[WTBAUnitCostBottle-87111],
        t.[WTBAUnitCostCase]           = s.[WTBAUnitCostCase-87110],
        t.[WTBAVegan]                  = s.[WTBAVegan-87062],
        t.[WTIAAllocate]               = s.[WTIAAllocate-90100],
        t.[WTIAAllocationReservInt]    = s.[WTIAAllocationReservInt-90102],
        t.[WTIAAllocationisCurrent]    = s.[WTIAAllocationisCurrent-90104],
        t.[WTIAFullAllocationRequired] = s.[WTIAFullAllocationRequired-90101],
        t.[WTIALimitingQtyperSource]   = s.[WTIALimitingQtyperSource-90130],
        t.[WTIALimitingUnitType]       = s.[WTIALimitingUnitType-90140],
        t.[WTUSDonotPricePost]         = s.[WTUSDonotPricePost-88800],
        t.[WTUSSalesLimitation]        = s.[WTUSSalesLimitation-88030],
        t.[systemId]                   = s.[systemId-2000000000],
        t.[timestamp]                  = s.[timestamp-0],
        t.[UpdateDate]                 = GETDATE()
    FROM [WH].[gold].[Item27] t
    JOIN [Rahat_LH].[dbo].[item] s ON t.[No] = s.[No-1]
    -- Only join rows where hash differs
    JOIN (
        SELECT s2.[No-1] AS [No]
        FROM [Rahat_LH].[dbo].[item] s2
        JOIN (
            SELECT [No], HASHBYTES('SHA2_256', CONCAT(
                ISNULL([WTIAAllocJnlUnitofMeasure],''),'|',ISNULL([VendorItemNo],''),'|',
                ISNULL([WCINV08WHItemNo],''),'|',ISNULL([WTUSSalesLimAllocMethod],''),'|',
                ISNULL([LeadTimeCalculation],''),'|',ISNULL([WTBAClosureTypeCode],''),'|',
                ISNULL([WTBASubRegionCode],''),'|',ISNULL([WarehouseClassCode],''),'|',
                ISNULL([ItemDiscGroup],''),'|',ISNULL([WTBAWineColor],''),'|',
                ISNULL([WTUSCOLANo],''),'|',ISNULL([WTBAOriginRegionCode-87005],''),'|',
                ISNULL([WTBAVarietalCode],''),'|',ISNULL([WTBABrandNo],''),'|',
                ISNULL([WTBAVintageCode],''),'|',ISNULL([WTBAAlcoholTypeCode],''),'|',
                ISNULL([WCINV04PurchaserCode],''),'|',ISNULL([WTBALabelCode],''),'|',
                ISNULL([CountryRegionofOriginCode],''),'|',ISNULL([WCINV14ItemPortfolio],''),'|',
                ISNULL([GenProdPostingGroup],''),'|',ISNULL([InventoryPostingGroup],''),'|',
                ISNULL([VendorNo],''),'|',ISNULL([WTBABottleSize],''),'|',
                ISNULL([$Company],''),'|',ISNULL(CAST([AllowInvoiceDisc] AS VARCHAR),''),'|',
                ISNULL(CAST([AllowOnlineAdjustment] AS VARCHAR),''),'|',
                ISNULL([BaseUnitofMeasure],''),'|',ISNULL(CAST([Blocked] AS VARCHAR),''),'|',
                ISNULL([Description],''),'|',ISNULL([ItemCategoryCode],''),'|',
                ISNULL(CONVERT(VARCHAR,[LastDateModified],120),''),'|',
                ISNULL(CONVERT(VARCHAR,[LastDateTimeModified],120),''),'|',
                ISNULL(CAST([LastDirectCost] AS VARCHAR),''),'|',
                ISNULL([LastTimeModified],''),'|',ISNULL(CAST([NetWeight] AS VARCHAR),''),'|',
                ISNULL(CAST([PurchasingBlocked] AS VARCHAR),''),'|',
                ISNULL([SalesUnitofMeasure],''),'|',ISNULL([SearchDescription],''),'|',
                ISNULL(CAST([StandardCost] AS VARCHAR),''),'|',
                ISNULL(CONVERT(VARCHAR,[SystemCreatedAt],120),''),'|',
                ISNULL([SystemCreatedBy],''),'|',
                ISNULL(CONVERT(VARCHAR,[SystemModifiedAt],120),''),'|',
                ISNULL(CAST([UnitCost] AS VARCHAR),''),'|',
                ISNULL(CAST([UnitListPrice] AS VARCHAR),''),'|',
                ISNULL(CAST([UnitPrice] AS VARCHAR),''),'|',
                ISNULL(CAST([UnitVolume] AS VARCHAR),''),'|',
                ISNULL(CAST([UseCrossDocking] AS VARCHAR),''),'|',
                ISNULL(CAST([WCAR06SalesCommissionable] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINT02ExportedtoJFHB] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINT03ExportedtoMMK] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINT04PABlocked] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINT04SplitAllowed] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINV08AgedInventory] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINV08ExpectedQtyfromVend] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINV08NAforSalesreps] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINV08SuggestedRetailPrice] AS VARCHAR),''),'|',
                ISNULL(CAST([WCINV19DonotPrintonCat] AS VARCHAR),''),'|',
                ISNULL(CAST([WCSAL04AllowPalletDiscount] AS VARCHAR),''),'|',
                ISNULL(CAST([WCSAL04AllowSampleDiscount] AS VARCHAR),''),'|',
                ISNULL(CAST([WCTEWPrestige] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAAlcoholContent] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBABiodynamic] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBACasePack] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBACasesperPallet] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBACasesperPalletLayer] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBADoNotAllowSamples] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAExclfromSampleBudget] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBALastDirectCostBottle] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBALastDirectCostCase] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBALayersperPallet] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAOrganic] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAProof] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBASalesOrderReview] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAStandardCostBottle] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAStandardCostCase] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAUnitCostBottle] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAUnitCostCase] AS VARCHAR),''),'|',
                ISNULL(CAST([WTBAVegan] AS VARCHAR),''),'|',
                ISNULL(CAST([WTIAAllocate] AS VARCHAR),''),'|',
                ISNULL([WTIAAllocationReservInt],''),'|',
                ISNULL(CAST([WTIAAllocationisCurrent] AS VARCHAR),''),'|',
                ISNULL(CAST([WTIAFullAllocationRequired] AS VARCHAR),''),'|',
                ISNULL(CAST([WTIALimitingQtyperSource] AS VARCHAR),''),'|',
                ISNULL([WTIALimitingUnitType],''),'|',
                ISNULL(CAST([WTUSDonotPricePost] AS VARCHAR),''),'|',
                ISNULL([WTUSSalesLimitation],''),'|',
                ISNULL([systemId],''),'|',
                ISNULL(CAST([timestamp] AS VARCHAR),'')
            )) AS dst_hash
            FROM [WH].[gold].[Item27]
        ) d ON s2.[No-1] = d.[No]
        WHERE HASHBYTES('SHA2_256', CONCAT(
            ISNULL(s2.[WTIAAllocJnlUnitofMeasure-90107],''),'|',
            ISNULL(s2.[VendorItemNo-32],''),'|',
            ISNULL(s2.[WCINV08WHItemNo-50045],''),'|',
            ISNULL(s2.[WTUSSalesLimAllocMethod-88035],''),'|',
            ISNULL(s2.[LeadTimeCalculation-33],''),'|',
            ISNULL(s2.[WTBAClosureTypeCode-87065],''),'|',
            ISNULL(s2.[WTBASubRegionCode-87006],''),'|',
            ISNULL(s2.[WarehouseClassCode-7300],''),'|',
            ISNULL(s2.[ItemDiscGroup-14],''),'|',
            ISNULL(s2.[WTBAWineColor-87025],''),'|',
            ISNULL(s2.[WTUSCOLANo-88500],''),'|',
            ISNULL(s2.[WTBAOriginRegionCode-87005],''),'|',
            ISNULL(s2.[WTBAVarietalCode-87007],''),'|',
            ISNULL(s2.[WTBABrandNo-87150],''),'|',
            ISNULL(s2.[WTBAVintageCode-87000],''),'|',
            ISNULL(s2.[WTBAAlcoholTypeCode-87015],''),'|',
            ISNULL(s2.[WCINV04PurchaserCode-50010],''),'|',
            ISNULL(s2.[WTBALabelCode-87080],''),'|',
            ISNULL(s2.[CountryRegionofOriginCode-95],''),'|',
            ISNULL(s2.[WCINV14ItemPortfolio-50150],''),'|',
            ISNULL(s2.[GenProdPostingGroup-91],''),'|',
            ISNULL(s2.[InventoryPostingGroup-11],''),'|',
            ISNULL(s2.[VendorNo-31],''),'|',
            ISNULL(s2.[WTBABottleSize-87020],''),'|',
            ISNULL(s2.[$Company],''),'|',
            ISNULL(CAST(s2.[AllowInvoiceDisc-15] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[AllowOnlineAdjustment-30] AS VARCHAR),''),'|',
            ISNULL(s2.[BaseUnitofMeasure-8],''),'|',
            ISNULL(CAST(s2.[Blocked-54] AS VARCHAR),''),'|',
            ISNULL(s2.[Description-3],''),'|',
            ISNULL(s2.[ItemCategoryCode-5702],''),'|',
            ISNULL(CONVERT(VARCHAR,s2.[LastDateModified-62],120),''),'|',
            ISNULL(CONVERT(VARCHAR,s2.[LastDateTimeModified-61],120),''),'|',
            ISNULL(CAST(s2.[LastDirectCost-25] AS VARCHAR),''),'|',
            ISNULL(s2.[LastTimeModified-63],''),'|',
            ISNULL(CAST(s2.[NetWeight-42] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[PurchasingBlocked-8004] AS VARCHAR),''),'|',
            ISNULL(s2.[SalesUnitofMeasure-5425],''),'|',
            ISNULL(s2.[SearchDescription-4],''),'|',
            ISNULL(CAST(s2.[StandardCost-24] AS VARCHAR),''),'|',
            ISNULL(CONVERT(VARCHAR,s2.[SystemCreatedAt-2000000001],120),''),'|',
            ISNULL(s2.[SystemCreatedBy-2000000002],''),'|',
            ISNULL(CONVERT(VARCHAR,s2.[SystemModifiedAt-2000000003],120),''),'|',
            ISNULL(CAST(s2.[UnitCost-22] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[UnitListPrice-38] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[UnitPrice-18] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[UnitVolume-44] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[UseCrossDocking-7384] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCAR06SalesCommissionable-50100] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINT02ExportedtoJFHB-50250] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINT03ExportedtoMMK-50280] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINT04PABlocked-50650] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINT04SplitAllowed-50651] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINV08AgedInventory-50043] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINV08ExpectedQtyfromVend-50044] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINV08NAforSalesreps-50046] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINV08SuggestedRetailPrice-50047] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCINV19DonotPrintonCat-50520] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCSAL04AllowPalletDiscount-50121] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCSAL04AllowSampleDiscount-50120] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WCTEWPrestige-50000] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAAlcoholContent-87030] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBABiodynamic-87064] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBACasePack-87010] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBACasesperPallet-87096] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBACasesperPalletLayer-87090] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBADoNotAllowSamples-87700] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAExclfromSampleBudget-87701] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBALastDirectCostBottle-87116] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBALastDirectCostCase-87115] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBALayersperPallet-87095] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAOrganic-87063] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAProof-87031] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBASalesOrderReview-87850] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAStandardCostBottle-87121] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAStandardCostCase-87120] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAUnitCostBottle-87111] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAUnitCostCase-87110] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTBAVegan-87062] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTIAAllocate-90100] AS VARCHAR),''),'|',
            ISNULL(s2.[WTIAAllocationReservInt-90102],''),'|',
            ISNULL(CAST(s2.[WTIAAllocationisCurrent-90104] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTIAFullAllocationRequired-90101] AS VARCHAR),''),'|',
            ISNULL(CAST(s2.[WTIALimitingQtyperSource-90130] AS VARCHAR),''),'|',
            ISNULL(s2.[WTIALimitingUnitType-90140],''),'|',
            ISNULL(CAST(s2.[WTUSDonotPricePost-88800] AS VARCHAR),''),'|',
            ISNULL(s2.[WTUSSalesLimitation-88030],''),'|',
            ISNULL(s2.[systemId-2000000000],''),'|',
            ISNULL(CAST(s2.[timestamp-0] AS VARCHAR),'')
        )) <> d.dst_hash
    ) changed ON t.[No] = changed.[No];

    -- =====================================================
    -- DELETE: Remove rows no longer in source
    -- =====================================================
    PRINT 'DELETE STARTED';
    DELETE t FROM [WH].[gold].[Item27] t
    LEFT JOIN [Rahat_LH].[dbo].[item] s ON t.[No] = s.[No-1]
    WHERE s.[No-1] IS NULL;

END

EXEC sp_Load_DimItemHash