CREATE TABLE [silver].[CustLedgerEntry21] (

	[GlobalDimension1Code-23] varchar(max) NULL, 
	[ExternalDocumentNo-63] varchar(max) NULL, 
	[SalespersonCode-25] varchar(max) NULL, 
	[Description-7] varchar(max) NULL, 
	[CustomerNo-3] varchar(max) NULL, 
	[$Company] varchar(max) NULL, 
	[$DeliveredDateTime] datetime2(3) NULL, 
	[AppliestoDocType-34] varchar(max) NULL, 
	[CustomerName-8] varchar(max) NULL, 
	[CustomerPostingGroup-22] varchar(max) NULL, 
	[DocumentDate-62] date NULL, 
	[DocumentNo-6] varchar(max) NULL, 
	[DocumentType-5] varchar(max) NULL, 
	[DueDate-37] date NULL, 
	[EntryNo-1] int NULL, 
	[InvDiscountLCY-20] real NULL, 
	[PostingDate-4] date NULL, 
	[ProfitLCY-19] real NULL, 
	[SalesLCY-18] real NULL, 
	[SelltoCustomerNo-21] varchar(max) NULL, 
	[SystemCreatedAt-2000000001] datetime2(3) NULL, 
	[SystemCreatedBy-2000000002] varchar(max) NULL, 
	[SystemModifiedAt-2000000003] datetime2(3) NULL, 
	[TransactionNo-53] int NULL, 
	[systemId-2000000000] varchar(max) NULL, 
	[timestamp-0] int NULL, 
	[InsertDate] datetime2(3) NULL, 
	[UpdateDate] datetime2(3) NULL
);