CREATE TABLE [silver].[ItemLedgerEntry32] (

	[$Company] varchar(max) NULL, 
	[EntryNo-1] int NULL, 
	[EntryType-4] varchar(max) NULL, 
	[DocumentNo-6] varchar(max) NULL, 
	[ItemNo-2] varchar(max) NULL, 
	[Description-7] varchar(max) NULL, 
	[PostingDate-3] date NULL, 
	[DocumentDate-60] date NULL, 
	[Quantity-12] real NULL, 
	[RemainingQuantity-13] real NULL, 
	[LocationCode-8] varchar(20) NULL, 
	[GlobalDimension1Code-33] varchar(max) NULL, 
	[ShptMethodCode-40] varchar(max) NULL, 
	[SourceType-41] varchar(max) NULL, 
	[SourceNo-5] varchar(max) NULL, 
	[UnitofMeasureCode-5407] varchar(max) NULL, 
	[WTBALiters-87300] real NULL, 
	[WTBAGallons-87301] real NULL, 
	[SystemCreatedAt-2000000001] datetime2(3) NULL, 
	[SystemCreatedBy-2000000002] varchar(max) NULL, 
	[SystemModifiedAt-2000000003] datetime2(3) NULL, 
	[systemId-2000000000] varchar(max) NULL, 
	[timestamp-0] int NULL, 
	[InsertDate] datetime2(3) NULL, 
	[UpdateDate] datetime2(3) NULL
);