CREATE TABLE [silver].[WTBAProducer87156] (

	[ProducerTypeCode-530] varchar(max) NULL, 
	[HomePage-150] varchar(max) NULL, 
	[Address2-50] varchar(max) NULL, 
	[FDARegExpirationDate-810] date NULL, 
	[Name2-30] varchar(max) NULL, 
	[FDARegistrationNo-800] varchar(max) NULL, 
	[FaxNo-130] varchar(max) NULL, 
	[County-80] varchar(max) NULL, 
	[CountryRegionCode-90] varchar(max) NULL, 
	[Email-140] varchar(max) NULL, 
	[PhoneNo-120] varchar(max) NULL, 
	[PostCode-70] varchar(max) NULL, 
	[Address-40] varchar(max) NULL, 
	[City-60] varchar(max) NULL, 
	[Name-20] varchar(max) NULL, 
	[SearchName-160] varchar(max) NULL, 
	[VendorNo-10] varchar(max) NULL, 
	[$Company] varchar(max) NULL, 
	[$DeliveredDateTime] datetime2(3) NULL, 
	[ExcludeFromWebsite-510] bit NULL, 
	[No-1] varchar(max) NULL, 
	[SmallWinery-610] bit NULL, 
	[SystemCreatedAt-2000000001] datetime2(3) NULL, 
	[SystemCreatedBy-2000000002] varchar(max) NULL, 
	[SystemModifiedAt-2000000003] datetime2(3) NULL, 
	[systemId-2000000000] varchar(max) NULL, 
	[timestamp-0] int NULL, 
	[InsertDate] datetime2(3) NULL, 
	[UpdateDate] datetime2(3) NULL
);