CREATE TABLE [silver].[WTIAAllocSalesLineEntry90107] (

	[SourceNo-290] varchar(max) NULL, 
	[AllocationCode-10] varchar(max) NULL, 
	[AllocLedgEntryLocationCode-180] varchar(max) NULL, 
	[ItemNo-20] varchar(max) NULL, 
	[UnitofMeasureCode-40] varchar(max) NULL, 
	[BaseUnitofMeasureCode-70] varchar(max) NULL, 
	[LocationCode-100] varchar(max) NULL, 
	[DocumentType-1] varchar(max) NULL, 
	[DocumentNo-2] varchar(max) NULL, 
	[DocumentLineNo-3] int NULL, 
	[LineNo-4] int NULL, 
	[Quantity-30] real NULL, 
	[QuantityBase-50] real NULL, 
	[QuantityCase-51] real NULL, 
	[QuantityBottle-52] real NULL, 
	[QtyperUnitOfMeasure-60] real NULL, 
	[TransactionType-80] varchar(max) NULL, 
	[AppliestoEntryNo-90] int NULL, 
	[QUantityShipped-160] real NULL, 
	[QuantityShippedBase-165] real NULL, 
	[QuantitytoShip-170] real NULL, 
	[QuantitytoShipBase-175] real NULL, 
	[SourceType-280] varchar(max) NULL, 
	[timestamp-0] int NULL, 
	[systemId-2000000000] varchar(max) NULL, 
	[SystemCreatedAt-2000000001] datetime2(3) NULL, 
	[SystemCreatedBy-2000000002] varchar(max) NULL, 
	[SystemModifiedAt-2000000003] datetime2(3) NULL, 
	[$Company] varchar(max) NULL, 
	[$DeliveredDateTime] datetime2(3) NULL, 
	[InsertDate] datetime2(3) NULL, 
	[UpdateDate] datetime2(3) NULL
);