CREATE TABLE [silver].[WTUSSLACustomerLicense88100] (

	[EffectiveDate-50] date NULL, 
	[LicenseNoSuffix-35] varchar(max) NULL, 
	[ErrorMessage-1010] varchar(max) NULL, 
	[LicenseCreditCode-120] varchar(max) NULL, 
	[LicenseNoPrefix-30] varchar(max) NULL, 
	[ExpirationDate-60] date NULL, 
	[LicenseNo-40] varchar(max) NULL, 
	[LicenseTypeCode-20] varchar(max) NULL, 
	[LicenseStatusCode-90] varchar(max) NULL, 
	[$Company] varchar(max) NULL, 
	[$DeliveredDateTime] datetime2(3) NULL, 
	[County-110] varchar(max) NULL, 
	[CustomerNo-10] varchar(max) NULL, 
	[Default-100] bit NULL, 
	[Delinquent-70] bit NULL, 
	[EntryNo-1] int NULL, 
	[ErrorFlag-1000] bit NULL, 
	[LastUpdateDate-500] datetime2(3) NULL, 
	[LastUpdateEntryNo-510] int NULL, 
	[LicenseStatus-300] varchar(max) NULL, 
	[SystemCreatedAt-2000000001] datetime2(3) NULL, 
	[SystemCreatedBy-2000000002] varchar(max) NULL, 
	[SystemModifiedAt-2000000003] datetime2(3) NULL, 
	[systemId-2000000000] varchar(max) NULL, 
	[timestamp-0] int NULL, 
	[InsertDate] datetime2(3) NULL, 
	[UpdateDate] datetime2(3) NULL
);