[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "item_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared item = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/uqhnqno2ltdqxs6iwnl59/Item-Sample-data.xlsx?rlkey=a18223vi4l1wwkrc4sc4cfndi&st=yxoti300&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "item", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ApplicationWkshUserID-521", type text}, {"WTIAAllocJnlUnitofMeasure-90107", type text}, {"PutawayUnitofMeasureCode-7307", type text}, {"GTIN-1217", type text}, {"VendorItemNo-32", type text}, {"WCINV08WHItemNo-50045", type text}, {"WTUSSalesLimAllocMethod-88035", type text}, {"LeadTimeCalculation-33", type text}, {"WTBAClosureTypeCode-87065", type text}, {"WTBASubRegionCode-87006", type text}, {"WarehouseClassCode-7300", type text}, {"ItemDiscGroup-14", type text}, {"WTBAWineColor-87025", type text}, {"WTUSCOLANo-88500", type text}, {"WTBAOriginRegionCode-87005", type text}, {"WTBAVarietalCode-87007", type text}, {"WTBABrandNo-87150", type text}, {"WTBAAlcoholTypeCode-87015", type text}, {"WCINV04PurchaserCode-50010", type text}, {"WTBALabelCode-87080", type text}, {"CountryRegionofOriginCode-95", type text}, {"WCINV14ItemPortfolio-50150", type text}, {"GenProdPostingGroup-91", type text}, {"InventoryPostingGroup-11", type text}, {"VendorNo-31", type text}, {"WTBABottleSize-87020", type text}, {"$Company", type text}, {"$DeliveredDateTime", type datetime}, {"AllowInvoiceDisc-15", Int64.Type}, {"AllowOnlineAdjustment-30", Int64.Type}, {"AssemblyPolicy-910", type text}, {"AutomaticExtTexts-96", Int64.Type}, {"BaseUnitofMeasure-8", type text}, {"Blocked-54", Int64.Type}, {"BudgetProfit-52", Int64.Type}, {"BudgetQuantity-50", Int64.Type}, {"BudgetedAmount-51", Int64.Type}, {"CarbonCreditPerUOM-6213", Int64.Type}, {"CommissionGroup-17", Int64.Type}, {"CostingMethod-21", type text}, {"CostisAdjusted-29", Int64.Type}, {"CoupledtoCRM-720", type text}, {"CreatedFromNonstockItem-5703", Int64.Type}, {"Critical-99000875", Int64.Type}, {"DampenerQuantity-5446", Int64.Type}, {"Description-3", type text}, {"DiscreteOrderQuantity-5410", Int64.Type}, {"DutyDue-39", Int64.Type}, {"DutyUnitConversion-48", Int64.Type}, {"ExcludedfromCostAdjustment-5801", Int64.Type}, {"FlushingMethod-5417", type text}, {"GHGCredit-6212", Int64.Type}, {"GenProdPostingGroupId-8007", type text}, {"GrossWeight-41", Int64.Type}, {"HasSalesForecast-21850", Int64.Type}, {"IncludeInventory-5441", Int64.Type}, {"IndirectCost-28", Int64.Type}, {"InventoryPostingGroupId-8006", type text}, {"InventoryValueZero-5409", Int64.Type}, {"ItemCategoryCode-5702", type text}, {"ItemCategoryId-8005", type text}, {"LastDateModified-62", type date}, {"LastDateTimeModified-61", type datetime}, {"LastDirectCost-25", type number}, {"LastTimeModified-63", type datetime}, {"LotSize-5401", Int64.Type}, {"LowLevelCode-5400", Int64.Type}, {"ManufacturingPolicy-5442", type text}, {"MaximumInventory-35", Int64.Type}, {"MaximumOrderQuantity-5412", Int64.Type}, {"MinimumOrderQuantity-5411", Int64.Type}, {"NetWeight-42", Int64.Type}, {"No-1", type text}, {"OrderMultiple-5414", Int64.Type}, {"OrderTrackingPolicy-99000773", type text}, {"OverflowLevel-5447", Int64.Type}, {"OverheadRate-99000757", Int64.Type}, {"PreventNegativeInventory-121", type text}, {"PriceIncludesVAT-87", Int64.Type}, {"PriceProfitCalculation-19", type text}, {"PriceUnitConversion-9", Int64.Type}, {"Profit-20", Int64.Type}, {"PurchUnitofMeasure-5426", type text}, {"PurchasingBlocked-8004", Int64.Type}, {"ReorderPoint-34", Int64.Type}, {"ReorderQuantity-36", Int64.Type}, {"ReorderingPolicy-5440", type text}, {"ReplenishmentSystem-5419", type text}, {"Reserve-100", type text}, {"RolledupCapOverheadCost-99000760", Int64.Type}, {"RolledupCapacityCost-5405", Int64.Type}, {"RolledupMaterialCost-5404", Int64.Type}, {"RolledupMfgOvhdCost-99000759", Int64.Type}, {"RolledupSubcontractedCost-99000758", Int64.Type}, {"RoundingPrecision-5422", Int64.Type}, {"SafetyStockQuantity-5413", Int64.Type}, {"SalesBlocked-8003", Int64.Type}, {"SalesUnitofMeasure-5425", type text}, {"Scrap-5407", Int64.Type}, {"SearchDescription-4", type text}, {"ServiceBlocked-8010", Int64.Type}, {"ServiceCommitmentOption-8052", type text}, {"SingleLevelCapOvhdCost-99000755", Int64.Type}, {"SingleLevelCapacityCost-99000753", Int64.Type}, {"SingleLevelMaterialCost-99000752", Int64.Type}, {"SingleLevelMfgOvhdCost-99000756", Int64.Type}, {"SingleLevelSubcontrdCost-99000754", Int64.Type}, {"StandardCost-24", Int64.Type}, {"StatisticsGroup-16", Int64.Type}, {"StockoutWarning-120", type text}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemModifiedAt-2000000003", type datetime}, {"TaxGroupId-8002", type text}, {"Type-10", type text}, {"UnitCost-22", type number}, {"UnitListPrice-38", Int64.Type}, {"UnitPrice-18", Int64.Type}, {"UnitVolume-44", type number}, {"UnitofMeasureId-8001", type text}, {"UnitsperParcel-43", Int64.Type}, {"UseCrossDocking-7384", Int64.Type}, {"VariantMandatoryifExists-122", type text}, {"WCAR06SalesCommissionable-50100", Int64.Type}, {"WCINT02ExportedtoJFHB-50250", Int64.Type}, {"WCINT03ExportedtoMMK-50280", Int64.Type}, {"WCINT04PABlocked-50650", Int64.Type}, {"WCINT04SplitAllowed-50651", Int64.Type}, {"WCINV08AgedInventory-50043", Int64.Type}, {"WCINV08ExpectedQtyfromVend-50044", Int64.Type}, {"WCINV08NAforSalesreps-50046", Int64.Type}, {"WCINV08SuggestedRetailPrice-50047", type number}, {"WCINV19DonotPrintonCat-50520", Int64.Type}, {"WCSAL04AllowPalletDiscount-50121", Int64.Type}, {"WCSAL04AllowSampleDiscount-50120", Int64.Type}, {"WCTEWPrestige-50000", Int64.Type}, {"WTBAAlcoholContent-87030", type number}, {"WTBABiodynamic-87064", Int64.Type}, {"WTBACasePack-87010", Int64.Type}, {"WTBACasesperPallet-87096", Int64.Type}, {"WTBACasesperPalletLayer-87090", Int64.Type}, {"WTBADoNotAllowSamples-87700", Int64.Type}, {"WTBAExclfromSampleBudget-87701", Int64.Type}, {"WTBALastDirectCostBottle-87116", type number}, {"WTBALastDirectCostCase-87115", type number}, {"WTBALayersperPallet-87095", Int64.Type}, {"WTBAOrganic-87063", Int64.Type}, {"WTBAProof-87031", type number}, {"WTBASalesOrderReview-87850", Int64.Type}, {"WTBAStandardCostBottle-87121", Int64.Type}, {"WTBAStandardCostCase-87120", Int64.Type}, {"WTBAUnitCostBottle-87111", type number}, {"WTBAUnitCostCase-87110", type number}, {"WTBAVegan-87062", Int64.Type}, {"WTIAAllocate-90100", Int64.Type}, {"WTIAAllocationReservInt-90102", type text}, {"WTIAAllocationisCurrent-90104", Int64.Type}, {"WTIAFullAllocationRequired-90101", Int64.Type}, {"WTIALimitingQtyperSource-90130", Int64.Type}, {"WTIALimitingUnitType-90140", type text}, {"WTUSDonotPricePost-88800", Int64.Type}, {"WTUSSalesLimitation-88030", type text}, {"systemId-2000000000", type text}, {"timestamp-0", Int64.Type}, {"InsertDate", type datetime}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type", {{"LastDateModified-62", type datetime}, {"UpdateDate", type datetime}, {"WTBAVintageCode-87000", type text}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type 1", {"InsertDate", "UpdateDate"})
in
  #"Removed columns";
shared item_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false, HierarchicalNavigation = null]),
  Navigation_1 = Pattern{[workspaceId = "f6a7e8bf-6fb8-46fb-bc50-09b1cb575eb7"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "5be1a843-3a24-405d-893e-d44dc466e5a2"]}[Data],
  TableNavigation = Navigation_2{[Id = "item", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
